// Regenerates js/data/certifications/index.js by inlining every per-cert
// metadata file into a single array. Eliminates the 48-file fanout on the
// critical path, consumers see one network request instead of 49.
//
// Source order: js/data/certifications/_manifest.js
// Source data:  js/data/certifications/<slug>.js (one per cert, each exports `cert`)
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath, pathToFileURL } from 'node:url';

const ROOT = path.dirname(path.dirname(fileURLToPath(import.meta.url)));
const DIR = path.join(ROOT, 'js', 'data', 'certifications');

const { order } = await import(pathToFileURL(path.join(DIR, '_manifest.js')).href);

const literals = [];
for (const slug of order) {
  const file = path.join(DIR, `${slug}.js`);
  const src = fs.readFileSync(file, 'utf8');
  const m = src.match(/export\s+const\s+cert\s*=\s*([\s\S]+?);\s*$/);
  if (!m) throw new Error(`Could not extract cert literal from ${slug}.js`);
  literals.push(m[1].trim());
}

const out = `// GENERATED by scripts/build-certs.mjs, do not hand-edit.
// Order comes from _manifest.js; data comes from <slug>.js files.
// Run \`npm run build:certs\` (or \`npm run build:seo\`) after editing either.
export const certifications = [
${literals.join(',\n')},
];
`;

fs.writeFileSync(path.join(DIR, 'index.js'), out);
console.log(`  ✓ js/data/certifications/index.js (${literals.length} certs bundled)`);
