// Regenerates js/data/certifications/index.js (light fields, all certs, eager on every
// page) and js/data/certifications/full/<slug>.js (heavy fields, one per cert, lazy-loaded
// only on that cert's own page) by reading every per-cert metadata file.
//
// Source order: js/data/certifications/_manifest.js
// Source data:  js/data/certifications/<slug>.js (one per cert, each exports `cert`)
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath, pathToFileURL } from 'node:url';

const ROOT = path.dirname(path.dirname(fileURLToPath(import.meta.url)));
const DIR = path.join(ROOT, 'js', 'data', 'certifications');
const FULL_DIR = path.join(DIR, 'full');

const { order } = await import(pathToFileURL(path.join(DIR, '_manifest.js')).href);

// Fields every page needs eagerly: home grid, nav domain count, related-certs matching,
// progress views, quiz/domain routing (confirmed by reading every consumer of this bundle).
// Everything else is only ever read on the cert's own page, so it moves to a per-slug lazy
// file that js/pages/certification/initCertification.js and js/components/certPreview/
// certPreview.js import by slug, mirroring the existing acronyms/services lazy-load pattern.
const LIGHT_FIELDS = ['slug', 'name', 'code', 'vendor', 'category', 'tagline', 'domains'];
// Read by exactly one cert's own page (renderCertHeader.js, affiliateLinksHTML.js) or the
// home-grid hover preview (certPreview.js) once narrowed to that one cert.
const FULL_FIELDS = ['about', 'details', 'officialSources', 'affiliates', 'udemyCourseUrl', 'extraUdemyCourses'];
// exam, faq, guide, seoName/seoTitle/seoH1/seoDescription are read only by
// scripts/build-seo.mjs at build time, which imports the per-cert source files directly,
// so they are never duplicated into a browser-facing bundle at all.

fs.mkdirSync(FULL_DIR, { recursive: true });

const lightCerts = [];
for (const slug of order) {
  const file = path.join(DIR, `${slug}.js`);
  const mod = await import(pathToFileURL(file).href);
  const cert = mod.cert;
  if (!cert) throw new Error(`Could not find \`export const cert\` in ${slug}.js`);

  const light = {};
  for (const f of LIGHT_FIELDS) if (cert[f] !== undefined) light[f] = cert[f];
  lightCerts.push(light);

  const full = {};
  for (const f of FULL_FIELDS) if (cert[f] !== undefined) full[f] = cert[f];
  fs.writeFileSync(
    path.join(FULL_DIR, `${slug}.js`),
    `// GENERATED by scripts/build-certs.mjs, do not hand-edit.\nexport const certFull = ${JSON.stringify(full, null, 2)};\n`
  );
}

const out = `// GENERATED by scripts/build-certs.mjs, do not hand-edit.
// Light index: only fields every page needs eagerly (see LIGHT_FIELDS in build-certs.mjs).
// Heavy per-cert fields (about, details, affiliates, ...) live in
// js/data/certifications/full/<slug>.js, lazy-loaded only on that cert's own page.
// Order comes from _manifest.js; data comes from <slug>.js files.
// Run \`npm run build:certs\` (or \`npm run build:seo\`) after editing either.
export const certifications = ${JSON.stringify(lightCerts, null, 2)};
`;

fs.writeFileSync(path.join(DIR, 'index.js'), out);
console.log(`  ✓ js/data/certifications/index.js (${lightCerts.length} certs, light fields only)`);
console.log(`  ✓ js/data/certifications/full/<slug>.js (${lightCerts.length} files, heavy fields lazy-loaded per cert)`);
